### ISSUE TITLE
Fix CI issues with dev-1.0.0

### ISSUE THREAD

**Issue by serut** [serut/meteor-coverage-app-exemple#6]
## Issues with circle.ci and travis.yml

https://circleci.com/gh/serut/meteor-coverage-app-exemple/84

```
meteor npm run test
> npm run lint --silent 
==> NOK
> meteor npm run coverage-app-unit && meteor npm run coverage-app-full
==> OK
> meteor npm run coverage-packages
==>  NOK
spacejam: spawning meteor
[[[[[ Tests ]]]]]
=> Started proxy.
MINISAT-out: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
MINISAT-err: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
/home/travis/.meteor/packages/meteor-tool/.1.4.1_1.cuijsq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^
abort() at Error
    at jsStackTrace (packages/logic-solver/minisat.js:3:1)
    at stackTrace (packages/logic-solver/minisat.js:3:1)
```
- [ ] Fix lint  
- [x] MINISAT-out: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
## Issues with spacejam

```
meteor npm run test-packages
> spacejam-mocha test-packages --full-app
spacjam: Warning: No packages matching test-packages have been found. Will add it to the meteor command line anyway, in case it's in PACKAGE_DIRS.
spacejam: spawning meteor
=> Errors while collecting tests:

While trying to test package `test-packages`:
error: Not a known local package, cannot test

spacejam: meteor exited with code: 1
spacejam: meteor is crashing server side. Exiting.
```
- [x] spacejam-mocha is a shortcut for meteor test-packages, so needs to 
  - rename spacejam-mocha into spacejam-packages-mocha
  - create a new spacejam-app-mocha
  - rename meteor-mocha into meteor-packages-mocha
  - create a new meteor-app-mocha
  - replace `#!/usr/bin/env bash` into `#!/usr/bin/env node` (cross  platform) and make corresponding modifications
## Issues with travis.yml
- [x] Replace meteor npm run coverage-packages-mocha into meteor npm run coverage-packages

**Comment by amarakgec** [comment]
@serut please send me simple example for meteor application like TODO application to understand how to implement code Coverage...

**Comment by serut** [comment]
See https://github.com/apollostack/meteor-starter-kit/pull/34/files

**Comment by amarakgec** [comment]
@serut One more Suggestion Sir
record complete video tutorial  code coverage for meteor Application and upload it on Youtube.
Its very helpful for developer to implement it on own project..
its Request
