### ISSUE TITLE
cultofcoders:mocha-console-runner doesn't exist

### ISSUE THREAD

**Issue by sebakerckhof** [serut/meteor-coverage-app-exemple#9]
The readme refers a lot to a `cultofcoders:mocha-console-runner` package, which doesn't seem to exist.
Did you mean `practicalmeteor:mocha-console-runner` ?

**Comment by serut** [comment]
No, you can't run `spacejam` with `practicalmeteor:mocha-console-runner` as `practicalmeteor:mocha` can't be used anymore on Meteor 1.6. So I asked @theodorDiaconu to deploy a fork of `practicalmeteor:mocha-console-runner` that uses `cultofcoders:mocha`, which will be `cultofcoders:mocha-console-runner`.

**Comment by theodorDiaconu** [comment]
@serut sorry about that! Can you point me to where did you ask me ? :D

**Comment by serut** [comment]
There https://github.com/practicalmeteor/meteor-mocha/issues/99 :1st_place_medal:

**Comment by sebakerckhof** [comment]
Btw, I meant to open this issue in https://github.com/serut/meteor-coverage/ , just saw I opened it in the wrong repo. But I was talking about the readme of https://github.com/serut/meteor-coverage/ as you probably guessed.

**Comment by serut** [comment]
Yeap I get it. This repository is 100% deprecated

**Comment by serut** [comment]
We now use meteortesting, this issue is no longer interesting.
